<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="OopsConcept\AbstractionAndInterfaces\" />
    <Folder Include="OopsConcept\AccessModifier\" />
    <Folder Include="OopsConcept\Delegates\" />
  </ItemGroup>

</Project>
